import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEnum,
  IsNotEmpty,
  IsOptional,
  IsString,
  Length,
} from 'class-validator';

export class RegisterNotificationDeviceDto {
  @ApiProperty({
    description: 'Stable app/device identifier (generated by mobile app)',
    example: 'a1b2c3d4-device-id',
  })
  @IsString()
  @IsNotEmpty()
  @Length(1, 200)
  deviceId!: string;

  @ApiProperty({
    description: 'Mobile platform',
    enum: ['android', 'ios'],
    example: 'android',
  })
  @IsEnum(['android', 'ios'])
  platform!: 'android' | 'ios';

  @ApiProperty({
    description: 'Firebase Cloud Messaging token',
    example: 'fcm-token-value',
  })
  @IsString()
  @IsNotEmpty()
  fcmToken!: string;

  @ApiPropertyOptional({
    description: 'Current app version on device',
    example: '1.2.0',
  })
  @IsOptional()
  @IsString()
  @Length(1, 50)
  appVersion?: string;

  @ApiPropertyOptional({
    description: 'Device/app locale',
    example: 'en-US',
  })
  @IsOptional()
  @IsString()
  @Length(2, 20)
  locale?: string;
}
