import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsNotEmpty,
  IsOptional,
  IsString,
  Length,
  Matches,
} from 'class-validator';

export class RegisterDeviceWithCodeDto {
  @ApiProperty({
    description: 'One-time registration code generated by the user',
    example: 'A1B2C3D4',
  })
  @IsString()
  @IsNotEmpty()
  @Length(8, 8)
  @Matches(/^[A-Z0-9]{8}$/, {
    message: 'code must be 8 uppercase alphanumeric characters',
  })
  code!: string;

  @ApiProperty({
    description: 'MAC address of the device (e.g., AA:BB:CC:DD:EE:FF)',
    example: 'AA:BB:CC:DD:EE:FF',
  })
  @IsString()
  @IsNotEmpty()
  @Matches(/^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$/, {
    message:
      'macAddress must be a valid MAC address in format XX:XX:XX:XX:XX:XX',
  })
  macAddress!: string;

  @ApiPropertyOptional({
    description: 'Optional friendly name for the device',
    example: 'ESP32 Kitchen Sensor',
  })
  @IsOptional()
  @IsString()
  @Length(1, 100)
  name?: string;

  @ApiProperty({
    description:
      'MQTT password. Must be at least 8 characters and include uppercase, lowercase, number, and special character.',
    example: 'Akram209!',
  })
  @IsString()
  @IsNotEmpty()
  @Matches(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,}$/, {
    message:
      'mqtt_pass must be at least 8 characters and include uppercase, lowercase, number, and special character',
  })
  mqtt_pass!: string;
}
